### ISSUE TITLE
Es necesitario revisar el fomato de los mazos?

### ISSUE THREAD

**Issue by v4rgas** [RodrigoToroIcarte/IIC2113-2023-1#129]
Queria saber si era necesario revisar que en los .txt que representan los mazos ocurra que
- Haya solo una carta con la forma ```Nombre (Superstar Card)```
- Que la Superstar Card este siempre en la parte de arriba del archivo
- Que todas las cartas que esten escritas en .txt existan en el json

**Comment by RodrigoToroIcarte** [comment]
No es necesario. Seremos consistentes con esas 3 cosas. Ver: https://github.com/RodrigoToroIcarte/IIC2113-2023-1/issues/123

**Comment by v4rgas** [comment]
wena muchas gracias
