### ISSUE TITLE
Duda sobre Clean Code: Objetos y Estructuras de Datos

### ISSUE THREAD

**Issue by v4rgas** [RodrigoToroIcarte/IIC2113-2023-1#138]
En mi codigo hay una relacion asi
Game -> Player -> Deck ->  Superstar, Card

En el Game necesito saber el nombre de Superstar para poder imprimirlo a la consola

Se me ocurren unas opciones y me gustaria saber cual seria mejor
1. Creo un metodo Player.GetSuperstarName() que retorne el nombre de la superstar
2. Creo un metodo Player.GetSuperstar() que retorne un Superstar y accedo a su .Name
3. Player.MetodoSinNombreAun(View view) que use view para imprimir lo que quiero
4. 1 o 2 Pero con una propiedad (Player.Superstar.Name)

El otro tema es que hacer cuando quiero comparar los valores de las Superstar de cada jugador,

Deberia hacer un metodo para obtener este valor o algo como la opcion 3?

Por ahora es un metodo  ```Game.GetPlayerWithMoreSuperstarValue(Player p1, Player p2)``` que accede a Player.Superstar.SuperstarValue, donde Player.Superstar retorna Deck.Superstar

Por ahora todo funciona bien pero hago esta pregunta para aprender sobre como deberia ser

**Comment by v4rgas** [comment]
al final cree una clase Cards la cual es una coleccion de cartas, cambie Deck a un struct con { Superstar superstar, Cards cards } y solo se utiliza para inicializar Player el cual guarda dentro de si un Cards Arsenal y Superstar superstar

**Comment by RodrigoToroIcarte** [comment]
Igual no es necesario que sea un `struct` para que se considere una estructura de datos. Podría ser un `class` con sus atributos públicos y también estaría bien. Lo comento por si acaso.
