### ISSUE TITLE
Uso adecuado de get/set

### ISSUE THREAD

**Issue by MartinAracena** [RodrigoToroIcarte/IIC2113-2023-1#170]
Buenas,
Edite y reformule mi duda, que es la siguiente.

No entiendo la forma de uso de las interfaces. Por ejemplo, si creo una clase Card, que hereda de la interfaz IViewableCard, deberia usar simplemente cada atributo con getters para conectar ambas? Pero de esta manera estaria violando una de las reglas de las clases en clean code. Por lo que, no entiendo bien como heredar de las interfaces sin violar condiciones de clean code.

Ademas, otra duda que tengo, es que en mi entrega 1, me quede un monton de tiempo pegado en como mantener los atributos de mi clase Card privados, pero en ultima instancia opte por dejar los atributos publicos para poder deserializar el json de las cartas y directamente crear cada carta. Como ahora en la entrega 2, eso seria una violacion de clean code, como podria hacer lo mismo? Estuve viendo que en alguna parte de clean code decia que se podia tener una clase especifica con atributos publicos o algo asi, que estuviera encargada de crear los datos/clases con atributos privados, pero me estoy confundiendo de lo que esta permitido de lo que no. Al final del dia, solamente quiero deserializar la informacion del json de las cartas y tenerlas guardadas, pero no romper las reglas de clean code.

**Comment by RodrigoToroIcarte** [comment]
Acá hay una discusión sobre getters, setters y clean code: https://github.com/RodrigoToroIcarte/IIC2113-2023-1/issues/168

Usar un getter no necesariamente rompe la reglas de clean code. Sin embargo, en el problema que describes, puede que te estés complicando de más. En el capítulo 6 se distinguen entre dos grandes tipos de datos: clases y estructuras de datos. Las clases son las que deben tener los atributos privados, ojalá sin getters/setters, etc. Las estructuras de datos tienen por objetivo agrupar y compartir información dentro de tu programa. Ellas tienen atributos públicos o getters/setters y está bien. Cuando lees el json de las cartas el objeto que se usa es una estructura de datos con getters/setters públicos. Eso está perfecto. Si quieres, puedes hacer que esa estructura implemente la interfaz IViewableCard.

Esto no quita que tarde o temprano termines creando una "clase" carta. La clase carta tiene sus atributos privados y provee métodos de alto nivel para acceder a su información. En su constructor podría recibir la estructura de datos con la información de la carta leída en el json. También podría tener un método de alto nivel, por ejemplo, un `ToString(...)` que retorne la información de la carta en el formato correcto. Ese método podría llamar a `Formatter.CardToString(...)` y darle como input la estructura de datos que leíste del json (que tiene guardada en un atributo privado).

**Comment by RodrigoToroIcarte** [comment]
Acabo de cachar que eres de mi sección. Mira las diapos de la clase 11. La clase Card que creo en el último ejemplo es una "clase" que recibe en el constructor la estructura de datos leída desde el json.

**Comment by MartinAracena** [comment]
Voy a mirarlo, tengo un par de dudas mas sobre que eventualmente tendre que tener una clase carta, porque efectivamente lo estoy usando como estructura de datos y ahora que me lo aclaras, puedo tener los atributos publicos, pero no entiendo el por que tendria que usar eventualmente una clase. Quizas porque voy a tener que usar metodos como ToString() como dijiste o quizas me perdi, pero mirando el codigo de la diapo quizas me aclare las dudas.

Gracias por la respuesta! Y perdon por lo tarde de la pregunta.

**Comment by RodrigoToroIcarte** [comment]
Si no sientes la necesidad de tener una clase carta no la agregues :)
