### ISSUE TITLE
Output esperado calza pero lo considera "Failed"

### ISSUE THREAD

**Issue by paulmacguire** [RodrigoToroIcarte/IIC2113-2023-1#172]
Hola,
Estaba rehaciendo mi E1 y limpiando el código, y ahora estaba viendo el tema de los outputs de los mazos que son inválidos. La cuestión es que no entiendo por qué estoy obteniendo un "failed" cuando mi output coincide exactamente con el test deseado. Adjunto imagenes al respecto:

Mi output:
![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/101202383/cc354b03-c008-4203-9acf-b4c2855e6238)

El output esperado:

![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/101202383/59cc10a2-cd17-49c4-80f4-6dda19f51db0)

Test:

![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/101202383/c378f0f1-898c-4d0e-ac73-aca101f25dd0)

Y estoy utilizando los métodos de la clase View:

![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/101202383/f31d52c7-be93-4c89-85dd-43df80bf1f8c)

![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/101202383/5df55cbb-1400-4354-bd06-a70eccdbd583)

**Comment by RodrigoToroIcarte** [comment]
¿Será culpa de los `static`? https://github.com/RodrigoToroIcarte/IIC2113-2023-1/issues/167

**Comment by paulmacguire** [comment]
Tengo algunos métodos que son static, pero por qué sería ese el problema?

**Comment by RodrigoToroIcarte** [comment]
Eso es lo que explico acá: https://github.com/RodrigoToroIcarte/IIC2113-2023-1/issues/167

... igual normalmente el problema se da cuando tienes atributos `static` (podría ser otra cosa). Pero lee ese issue. Si el problema no son los `static` podría ser que no estés usando el `_view` correctamente.

**Comment by paulmacguire** [comment]
Ahí corrí uno por uno los unit tests y me funcionaron, pero entonces qué hago? Lo dejo así o tengo que cambiar algo? (Estoy con los tests de la entrega 1 por si acaso, dejando todo listo para pasar a la entrega 2 y solo ajustar detalles)

También lo otro, quería saber si existe alguna posibilidad de saber las causas exactas de por qué tengo inválido un test en particular. Específicamente:

![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/101202383/304ec7f0-2838-4ba3-a4e5-b1d90005730b)

**Comment by RodrigoToroIcarte** [comment]
¡Hola!

Definitivamente tienes que arreglar el problema que tienes con los `static`.

Al menos el primer test de mazos inválidos que te falla es porque el mazo 11.txt es inválido. Ese mazo tiene dos veces la carta `Austin Elbow Smash`, que es `unique`.

**Comment by paulmacguire** [comment]
Perfecto. Y los demás, el Invalid Test 3 y el 4, cuáles serían las causas?

**Comment by RodrigoToroIcarte** [comment]
El test 4 creo que falla porque en un mazo de HHH había una carta de Mankind. No recuerdo porqué fallaba el test 3.
