### ISSUE TITLE
Problemas con bool dentro de condición

### ISSUE THREAD

**Issue by ebenstom** [RodrigoToroIcarte/IIC2113-2023-1#181]
Hola, he estado luchando un buen rato con un problema en mi código que tengo una condición a la que entra un bool, el cual varía entre true y false (no es siempre lo mismo). La cosa es que cuando su valor es true o false igual entra en la condición, entonces ya no se que hacer con eso.

Ya revisé en rider y efectivamente es un bool, también cuando el valor es true se sigue cumpliendo.

![Captura de pantalla 2023-09-23 031323](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/89204796/847410f2-7f72-4edc-a252-29497acc5063)

**Comment by RodrigoToroIcarte** [comment]
¡Hola!

El problema no se encuentra ahí. Si `temp` es `false` no se entra el if. El `False` que te aparece en consola debe ser de otro `WriteLine` que tienes en otro lado del código.

Si quieres puede usar el debugger para cachar qué está pasando. Basta con cliquear en el número de la línea donde quieres ver qué está pasando:
![Screenshot from 2023-09-23 11-57-33](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/7000518/b862ccfb-a414-4fe9-ace9-3b10de56816c)

y aparecerá un círculo rojo:

![Screenshot from 2023-09-23 11-57-45](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/7000518/1419f2ab-0a1c-4f5b-8239-909e4c33d0cd)

Luego en vez de correr el programa con el símbolo "Play" usas el bicho que aparece al lado:
![deb](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/7000518/deb647fd-03af-4325-8020-c3e78379903a)

Cuando el código llegue a la línea marcada se detiene:
![marcada](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/7000518/86205a57-0b6a-43c3-8618-103a7771dedc)

... ahí puedes ver el valor de variables, dejar que ejecute la siguiente línea (para saber si entra o no al if), entre otras cosas:
![siguiente](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/7000518/9f95ae0a-b316-4f23-b05e-263b899edbc2)

Básicamente puedes controlar lo que pasa con estos botones:
![Screenshot from 2023-09-23 11-58-34](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/7000518/288a0891-93ec-4d09-9615-c0bf3ae2df88)

**Comment by ebenstom** [comment]
mira, acá en la parte que lo defino sale temp: false 
![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/89204796/06f32774-3f91-4716-bc9d-315e1bacad0a)
Luego en el if por alguna razón muy misteriosa solo cambia a true sin que pase nada, literal cuando se ejecuta el evaluar la condicion se vuelve mágicamente true.
![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/89204796/1b04c1db-9acd-4762-88db-9fb60b41179b)
Entonces ahí termina entrando y escribe el Console.WriteLine
![image](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/89204796/c00ccb7a-98b9-4224-8c21-04aec3d95819)

**Comment by ebenstom** [comment]
Gracias, al final pasaba que los console.WriteLine que hice corrian la función varias veces y cambiaba el resultado, efectivamente con debugger pude notar que el código si funciona.
