### ISSUE TITLE
Duda habilidad de Mankind (Grupo de test 6-BasicHybridCards)

### ISSUE THREAD

**Issue by felipehen** [RodrigoToroIcarte/IIC2113-2023-1#184]
Hola! Tengo una duda con respecto a como se aplica la habilidad de Mankind en el los test case de las cartas híbridas. 

Como se ve en la imagen a continuación, en uno de los test case el oponente intenta infligirle 1 de daño a mankind, pero este es omitido, probablemente por su habilidad. 
![Captura de pantalla (499)](https://github.com/RodrigoToroIcarte/IIC2113-2023-1/assets/62078656/de8eb775-0885-4d48-b650-caddcf6ce1ec)

Sin embargo, si hago que mankind reduzca su daño incluso cuando solo recibe 1, hace que muchos otros test case pasen a ser incorrectos. 

Quiero recalcar que al ejecutar mi código, me entrega el mismo output, pero haciendo que Mankind reciba 1 de daño, junto con su correspondiente descarte de carta por daño. 

Este tase case corresponde al test case 4, aunque tambien ocurre en el 8. En el test 4, corresponde a la linea 470 (aproximadamente)
Por esto quiero preguntar, ¿Que esta pasando aqui? Muchas gracias de antemano.

**Comment by RodrigoToroIcarte** [comment]
No entiendo la pregunta :/

El test case que muestras está perfecto. Mankind, por su habilidad, recibe 1 menos de daño. En el ejemplo que muestras recibe 0 de daño.

Creo que el problema se encuentra en los otros test cases que dices que fallan si aplicas la habilidad de Mankind para reducir daño. ¿Cuáles son y por qué fallan?

**Comment by felipehen** [comment]
Ya no es necesario profe, era un error en mi codigo con un caso borde. Lei mal la E2 y aplique el descuento de daño para todo tipo de daño, no solamente daño hecho por cartas. 

Muchas gracias!
