### ISSUE TITLE
[Control capitulo 4 y 5] Fecha de entrega 

### ISSUE THREAD

**Issue by FrancoBrice** [RodrigoToroIcarte/IIC2113-2023-1#52]
Hola profesor, hoy ingresé a realizar el control de clean code y en canvas aparece que venció el plazo ayer, sin embargo, usted señaló en un anuncio que estaría disponible hasta el domingo. Le agradecería revisarlo. Saludos.

**Comment by RodrigoToroIcarte** [comment]
Que extraño. A mí me deja realizar el examen cuando me meto con la vista de estudiante. ¿Estás seguro que estás en el cuestionario correcto?

(lo que configuré fue que el plazo venciera el viernes pero igual pudieran responder el cuestionario hasta hoy a las 23:59)
